<h1 align="left">Workflow</h1>

In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:

- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & NumPy
- Using @tf.function (a way to speed up your regular Python functions)
- Using GPUs with TensorFlow (or TPUs)

<br>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


<br>

<h1 align="center">Introduction to Tensors</h1>

<br>

<h3 align="left">Creating tensors with tf.constant()</h3>

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor 

scalar.ndim

0

In [4]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector

vector.ndim

1

In [6]:
# Create a matrix (matrix has more than 1 dimension)

matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Let's create another matrix with float16 dtype

matrix2 = tf.constant([[10., 7.],
                       [3., 2.],
                       [8., 9.]],
                      dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

- By default, dtype with tf.constant() is int32 (32-bit precision).
- The higher the number of precision, the more **exact** these numbers are stored on your computer.
- So float16 < float32 for the same number n.
- This also means that the lower the precision, the less space it takes to store it on your computer.

In [9]:
matrix2.ndim

2

In [10]:
# Let's create a tensor (ndim > 2)

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]]])
tensor

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [11]:
tensor.ndim

3

In [12]:
tensor2 = tf.constant([[[1, 2, 3],
                        [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]]])
tensor2

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [13]:
tensor2.ndim

3

- Notice (look at the shapes of *tensor* and *tensor2*) how the dimensions are affected by where you place the square brackets.

<br>

What we've created so far:

* scalar: a single number
* vector: a number with direction (e.g. wind speed and direction)
* matrix: a 2-dimensional array of numbers
* tensor: an n-dimensional array of numbers

Notice that  

* 0-dimensional tensor is a scalar
* 1-dimensional tensor is a vector
* 2-dimensional tensor is a matrix

<br>

<h3 align="left">Creating tensors with tf.Variable()</h3>

In [14]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

In [15]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [16]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [17]:
# Let's try to change one of the elements in our changeable tensor

changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

- Notice that *tf.Variable()* objects are **mutable**.
- In Python, an object is considered *mutable*, if its value can be changed after creating it.

In [19]:
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

- Notice that *tf.constant()* objects are **immutable**.
- In Python, an object is considered *immutable*, if its value cannot be changed after it has been created.

**NOTE**

- Rarely in practice you will need to decide whether to use *tf.constant()* or *tf.variable()* to create tensors, as TensorFlow does this for you.

<br>

<h3 align="left">Creating random tensors</h3>

- Random tensors are tensors of some arbitrary size with random numbers.

In [ ]:
# Create two random (but the same) tensors.
# Set seed for reproducibility.

#random1 = tf.random.Generator.from_seed(42)
#random1 = random1.normal(shape=(3,2))

- Notice that the first line only initializes a new random number generator in TensorFlow using the seed value 42.
- This code (first line) itself does not create or initialize any tensor values.
- It only sets up a generator that can be used to create random values deterministically.
- The second code line then assigns random normally distributed data of the shape (3,2) into the random1 object.